Document: stomper
Title: Debian stomper Manual
Author: <insert document author here>
Abstract: This manual describes what stomper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/stomper/stomper.sgml.gz

Format: postscript
Files: /usr/share/doc/stomper/stomper.ps.gz

Format: text
Files: /usr/share/doc/stomper/stomper.text.gz

Format: HTML
Index: /usr/share/doc/stomper/html/index.html
Files: /usr/share/doc/stomper/html/*.html
